version: "3.4"
services:
  vite_docker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite_docker
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
