name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: estpumipat.0@gmail.com
          password: 0981075234Est

      - name: Build and Push Docker Image
        run: |
          docker build -t estpumipat/vite_docker:latest .
          docker push estpumipat/vite_docker:latest
        env:
          DOCKER_USERNAME: estpumipat.0@gmail.com
          DOCKER_PASSWORD: 0981075234Est
